Repository SSUMC-7th/Spring_Boot_B, pull requests merged in 2024-11, with the labels that each got.

#12 [Randy] Chapter 5. JPA 기초 및 프로젝트 구조
  src/main/java/umc/spring/Application.java
  src/main/java/umc/spring/domain/Comment.java
  src/main/java/umc/spring/domain/FoodCategory.java
  src/main/java/umc/spring/domain/Member.java
  src/main/java/umc/spring/domain/Mission.java
  src/main/java/umc/spring/domain/Region.java
  src/main/java/umc/spring/domain/Review.java
  src/main/java/umc/spring/domain/ReviewImage.java
  src/main/java/umc/spring/domain/Store.java
  src/main/java/umc/spring/domain/Terms.java
  src/main/java/umc/spring/domain/common/BaseEntity.java
  src/main/java/umc/spring/domain/enums/Gender.java
  src/main/java/umc/spring/domain/enums/MemberStatus.java
  src/main/java/umc/spring/domain/enums/MissionStatus.java
  src/main/java/umc/spring/domain/enums/SocialType.java
  src/main/java/umc/spring/domain/mapping/MemberAgree.java
  src/main/java/umc/spring/domain/mapping/MemberMission.java
  src/main/java/umc/spring/domain/mapping/MemberPrefer.java
  src/main/resources/application.yml
Labels: ✨ Chapter05

#13 [Nunu] Chapter 5. JPA 기초 및 프로젝트 구조
  spring/build.gradle
  spring/src/main/java/umc/spring/Application.java
  spring/src/main/java/umc/spring/domain/Comment.java
  spring/src/main/java/umc/spring/domain/FavoriteFood.java
  spring/src/main/java/umc/spring/domain/Member.java
  spring/src/main/java/umc/spring/domain/Mission.java
  spring/src/main/java/umc/spring/domain/Restaurant.java
  spring/src/main/java/umc/spring/domain/RestaurantImg.java
  spring/src/main/java/umc/spring/domain/Review.java
  spring/src/main/java/umc/spring/domain/common/BaseEntity.java
  spring/src/main/java/umc/spring/domain/enums/Food.java
  spring/src/main/java/umc/spring/domain/enums/Gender.java
  spring/src/main/java/umc/spring/domain/enums/MemberStatus.java
  spring/src/main/java/umc/spring/domain/enums/MissionStatus.java
  spring/src/main/java/umc/spring/domain/enums/SocialType.java
  spring/src/main/java/umc/spring/domain/mapping/MemberFavoriteFood.java
  spring/src/main/java/umc/spring/domain/mapping/MemberMission.java
Labels: ✨ Chapter05

#14 [Woody] Chapter 5. JPA 기초 및 프로젝트 구조
  spring/build.gradle
  spring/src/main/java/umc/spring/Application.java
  spring/src/main/java/umc/spring/domain/Food.java
  spring/src/main/java/umc/spring/domain/Member.java
  spring/src/main/java/umc/spring/domain/Mission.java
  spring/src/main/java/umc/spring/domain/Region.java
  spring/src/main/java/umc/spring/domain/Review.java
  spring/src/main/java/umc/spring/domain/Store.java
  spring/src/main/java/umc/spring/domain/Term.java
  spring/src/main/java/umc/spring/domain/common/BaseEntity.java
  spring/src/main/java/umc/spring/domain/enums/FoodCategory.java
  spring/src/main/java/umc/spring/domain/enums/Gender.java
  spring/src/main/java/umc/spring/domain/enums/MemberStatus.java
  spring/src/main/java/umc/spring/domain/enums/MissionStatus.java
  spring/src/main/java/umc/spring/domain/enums/SocialType.java
  spring/src/main/java/umc/spring/domain/mapping/MemberAgreeTerm.java
  spring/src/main/java/umc/spring/domain/mapping/MemberMission.java
  spring/src/main/java/umc/spring/domain/mapping/MemberPreferFood.java
  spring/src/main/resources/application.yml
Labels: ✨ Chapter05

#15 [Bingseok] Chapter 5. JPA 기초 및 프로젝트 구조
  src/main/java/umc/spring/Application.java
  src/main/java/umc/spring/domain/FoodCategory.java
  src/main/java/umc/spring/domain/Member.java
  src/main/java/umc/spring/domain/Mission.java
  src/main/java/umc/spring/domain/Region.java
  src/main/java/umc/spring/domain/Review.java
  src/main/java/umc/spring/domain/ReviewImage.java
  src/main/java/umc/spring/domain/Store.java
  src/main/java/umc/spring/domain/Terms.java
  src/main/java/umc/spring/domain/common/BaseEntity.java
  src/main/java/umc/spring/domain/enums/Gender.java
  src/main/java/umc/spring/domain/enums/MemberStatus.java
  src/main/java/umc/spring/domain/enums/SocialType.java
  src/main/java/umc/spring/domain/mapping/MemberAgree.java
  src/main/java/umc/spring/domain/mapping/MemberMission.java
  src/main/java/umc/spring/domain/mapping/MemberPrefer.java
  src/main/java/umc/spring/domain/mapping/MissionStatus.java
  src/main/resources/application.yml
Labels: ✨ Chapter05

#19 [Woody] Chapter 6. JPA 활용
  .idea/.gitignore
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  spring/build.gradle
  spring/src/main/generated/umc/spring/domain/QFood.java
  spring/src/main/generated/umc/spring/domain/QMember.java
  spring/src/main/generated/umc/spring/domain/QMission.java
  spring/src/main/generated/umc/spring/domain/QRegion.java
  spring/src/main/generated/umc/spring/domain/QReview.java
  spring/src/main/generated/umc/spring/domain/QStore.java
  spring/src/main/generated/umc/spring/domain/QTerm.java
  spring/src/main/generated/umc/spring/domain/common/QBaseEntity.java
  spring/src/main/generated/umc/spring/domain/mapping/QMemberAgreeTerm.java
  spring/src/main/generated/umc/spring/domain/mapping/QMemberMission.java
  spring/src/main/generated/umc/spring/domain/mapping/QMemberPreferFood.java
  spring/src/main/java/umc/spring/Application.java
  spring/src/main/java/umc/spring/config/QueryDSLConfig.java
  spring/src/main/java/umc/spring/domain/Review.java
  spring/src/main/java/umc/spring/domain/Store.java
  spring/src/main/java/umc/spring/domain/common/BaseEntity.java
  spring/src/main/java/umc/spring/repository/MemberMissionRepository/MemberMissionRepository.java
  spring/src/main/java/umc/spring/repository/MemberMissionRepository/MemberMissionRepositoryCustom.java
  spring/src/main/java/umc/spring/repository/MemberMissionRepository/MemberMissionRepositoryImpl.java
  spring/src/main/java/umc/spring/repository/MemberRepository/MemberRepository.java
  spring/src/main/java/umc/spring/repository/MemberRepository/MemberRepositoryCustom.java
  spring/src/main/java/umc/spring/repository/MemberRepository/MemberRepositoryImpl.java
  spring/src/main/java/umc/spring/repository/MissionRepository/MissionRepository.java
  spring/src/main/java/umc/spring/repository/MissionRepository/MissionRepositoryCustom.java
  spring/src/main/java/umc/spring/repository/MissionRepository/MissionRepositoryImpl.java
  spring/src/main/java/umc/spring/repository/ReviewRepository/ReviewRepository.java
  spring/src/main/java/umc/spring/repository/StoreRepository/StoreRepository.java
  spring/src/main/java/umc/spring/repository/StoreRepository/StoreRepositoryCustom.java
  spring/src/main/java/umc/spring/repository/StoreRepository/StoreRepositoryImpl.java
  spring/src/main/java/umc/spring/service/MemberMissionService/MemberMissionQueryService.java
  spring/src/main/java/umc/spring/service/MemberMissionService/MemberMissionQueryServiceImpl.java
  spring/src/main/java/umc/spring/service/MemberService/MemberQueryService.java
  spring/src/main/java/umc/spring/service/MemberService/MemberQueryServiceImpl.java
  spring/src/main/java/umc/spring/service/MissionService/MissionQueryService.java
  spring/src/main/java/umc/spring/service/MissionService/MissionQueryServiceImpl.java
  spring/src/main/java/umc/spring/service/ReviewService/ReviewQueryService.java
  spring/src/main/java/umc/spring/service/ReviewService/ReviewQueryServiceImpl.java
  spring/src/main/java/umc/spring/service/StoreService/StoreQueryService.java
  spring/src/main/java/umc/spring/service/StoreService/StoreQueryServiceImpl.java
  spring/src/main/resources/application.yml
Labels: ✨ Chapter06

#21 [Randy] Chapter 6. JPA 활용
  build.gradle
  src/main/generated/umc/spring/domain/QComment.java
  src/main/generated/umc/spring/domain/QFoodCategory.java
  src/main/generated/umc/spring/domain/QMember.java
  src/main/generated/umc/spring/domain/QMission.java
  src/main/generated/umc/spring/domain/QRegion.java
  src/main/generated/umc/spring/domain/QReview.java
  src/main/generated/umc/spring/domain/QReviewImage.java
  src/main/generated/umc/spring/domain/QStore.java
  src/main/generated/umc/spring/domain/QTerms.java
  src/main/generated/umc/spring/domain/common/QBaseEntity.java
  src/main/generated/umc/spring/domain/mapping/QMemberAgree.java
  src/main/generated/umc/spring/domain/mapping/QMemberMission.java
  src/main/generated/umc/spring/domain/mapping/QMemberPrefer.java
  src/main/java/umc/spring/Application.java
  src/main/java/umc/spring/config/QueryDSLConfig.java
  src/main/java/umc/spring/domain/Mission.java
  src/main/java/umc/spring/domain/Review.java
  src/main/java/umc/spring/domain/Store.java
  src/main/java/umc/spring/repository/MemberRepository/MemberRepository.java
  src/main/java/umc/spring/repository/MemberRepository/MemberRepositoryCustom.java
  src/main/java/umc/spring/repository/MemberRepository/MemberRepositoryImpl.java
  src/main/java/umc/spring/repository/MissionRepository/MissionRepository.java
  src/main/java/umc/spring/repository/MissionRepository/MissionRepositoryCustom.java
  src/main/java/umc/spring/repository/MissionRepository/MissionRepositoryImpl.java
  src/main/java/umc/spring/repository/ReviewRepository/ReviewRepository.java
  src/main/java/umc/spring/repository/ReviewRepository/ReviewRepositoryCustom.java
  src/main/java/umc/spring/repository/ReviewRepository/ReviewRepositoryImpl.java
  src/main/java/umc/spring/repository/StoreRepository/StoreRepository.java
  src/main/java/umc/spring/repository/StoreRepository/StoreRepositoryCustom.java
  src/main/java/umc/spring/repository/StoreRepository/StoreRepositoryImpl.java
  src/main/java/umc/spring/service/MemberService/MemberQueryService.java
  src/main/java/umc/spring/service/MemberService/MemberQueryServiceImpl.java
  src/main/java/umc/spring/service/MissionService/MissionQueryService.java
  src/main/java/umc/spring/service/MissionService/MissionQueryServiceImpl.java
  src/main/java/umc/spring/service/ReviewService/ReviewQueryService.java
  src/main/java/umc/spring/service/ReviewService/ReviewQueryServiceImpl.java
  src/main/java/umc/spring/service/StoreService/StoreQueryService.java
  src/main/java/umc/spring/service/StoreService/StoreQueryServiceImpl.java
Labels: ✨ Chapter06

#20 [Nunu/#6] Chapter 6. JPA 활용
  spring/build.gradle
  spring/src/main/generated/umc/spring/domain/QComment.java
  spring/src/main/generated/umc/spring/domain/QFavoriteFood.java
  spring/src/main/generated/umc/spring/domain/QMember.java
  spring/src/main/generated/umc/spring/domain/QMission.java
  spring/src/main/generated/umc/spring/domain/QRegion.java
  spring/src/main/generated/umc/spring/domain/QRestaurant.java
  spring/src/main/generated/umc/spring/domain/QRestaurantImg.java
  spring/src/main/generated/umc/spring/domain/QReview.java
  spring/src/main/generated/umc/spring/domain/common/QBaseEntity.java
  spring/src/main/generated/umc/spring/domain/mapping/QMemberFavoriteFood.java
  spring/src/main/generated/umc/spring/domain/mapping/QMemberMission.java
  spring/src/main/java/umc/spring/Application.java
  spring/src/main/java/umc/spring/config/QueryDSLConfig.java
  spring/src/main/java/umc/spring/domain/Region.java
  spring/src/main/java/umc/spring/domain/Restaurant.java
  spring/src/main/java/umc/spring/domain/Review.java
  spring/src/main/java/umc/spring/repository/restaurantRepository/RestaurantRepository.java
  spring/src/main/java/umc/spring/repository/restaurantRepository/RestaurantRepositoryCustom.java
  spring/src/main/java/umc/spring/repository/restaurantRepository/RestaurantRepositoryImpl.java
  spring/src/main/java/umc/spring/service/restaurantService/RestaurantQueryService.java
  spring/src/main/java/umc/spring/service/restaurantService/RestaurantQueryServiceImpl.java
Labels: ✨ Chapter06

#27 [Bingseok] Chapter 7. API 응답 통일 & 에러 핸들러
  build.gradle
  src/main/java/umc/spring/apiPayload/ApiResponse.java
  src/main/java/umc/spring/apiPayload/code/BaseCode.java
  src/main/java/umc/spring/apiPayload/code/BaseErrorCode.java
  src/main/java/umc/spring/apiPayload/code/ErrorReasonDTO.java
  src/main/java/umc/spring/apiPayload/code/ReasonDTO.java
  src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/spring/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc/spring/apiPayload/exception/ExceptionAdvice.java
  src/main/java/umc/spring/apiPayload/exception/GeneralException.java
  src/main/java/umc/spring/apiPayload/exception/handler/TempHandler.java
  src/main/java/umc/spring/converter/TempConverter.java
  src/main/java/umc/spring/service/TempService/TempCommandService.java
  src/main/java/umc/spring/service/TempService/TempCommandServiceImpl.java
  src/main/java/umc/spring/service/TempService/TempQueryService.java
  src/main/java/umc/spring/service/TempService/TempQueryServiceImpl.java
  src/main/java/umc/spring/web/controller/TempRestController.java
  src/main/java/umc/spring/web/dto/TempRequest.java
  src/main/java/umc/spring/web/dto/TempResponse.java
Labels: ✨ Chapter07

#26 [Woody] Chapter 7. API 응답 통일 & 에러 핸들러
  spring/build.gradle
  spring/src/main/java/umc/spring/apiPayload/ApiResponse.java
  spring/src/main/java/umc/spring/apiPayload/code/BaseCode.java
  spring/src/main/java/umc/spring/apiPayload/code/BaseErrorCode.java
  spring/src/main/java/umc/spring/apiPayload/code/ErrorReasonDTO.java
  spring/src/main/java/umc/spring/apiPayload/code/ReasonDTO.java
  spring/src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  spring/src/main/java/umc/spring/apiPayload/code/status/SuccessStatus.java
  spring/src/main/java/umc/spring/apiPayload/exception/ExceptionAdvice.java
  spring/src/main/java/umc/spring/apiPayload/exception/GeneralException.java
  spring/src/main/java/umc/spring/apiPayload/exception/handler/TempHandler.java
  spring/src/main/java/umc/spring/converter/TempConverter.java
  spring/src/main/java/umc/spring/service/TempService/TempCommandService.java
  spring/src/main/java/umc/spring/service/TempService/TempCommandServiceImpl.java
  spring/src/main/java/umc/spring/service/TempService/TempQueryService.java
  spring/src/main/java/umc/spring/service/TempService/TempQueryServiceImpl.java
  spring/src/main/java/umc/spring/web/controller/TempRestController.java
  spring/src/main/java/umc/spring/web/dto/TempRequest.java
  spring/src/main/java/umc/spring/web/dto/TempResponse.java
Labels: ✨ Chapter07

#24 [Randy] Chapter 7. API 응답 통일 & 에러 핸들러
  build.gradle
  src/main/java/umc/spring/Application.java
  src/main/java/umc/spring/apiPayload/ApiResponse.java
  src/main/java/umc/spring/apiPayload/code/BaseCode.java
  src/main/java/umc/spring/apiPayload/code/BaseErrorCode.java
  src/main/java/umc/spring/apiPayload/code/ErrorReasonDTO.java
  src/main/java/umc/spring/apiPayload/code/ReasonDTO.java
  src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/spring/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc/spring/apiPayload/exception/ExceptionAdvice.java
  src/main/java/umc/spring/apiPayload/exception/GeneralException.java
  src/main/java/umc/spring/apiPayload/exception/handler/TempHandler.java
  src/main/java/umc/spring/converter/TempConverter.java
  src/main/java/umc/spring/service/TempService/TempCommandService.java
  src/main/java/umc/spring/service/TempService/TempCommandServiceImpl.java
  src/main/java/umc/spring/service/TempService/TempQueryService.java
  src/main/java/umc/spring/service/TempService/TempQueryServiceImpl.java
  src/main/java/umc/spring/web/controller/TempRestController.java
  src/main/java/umc/spring/web/dto/TempReqeust.java
  src/main/java/umc/spring/web/dto/TempResponse.java
Labels: ✨ Chapter07

#25 [Nunu] Chapter 7. API 응답 통일 & 에러 핸들러
  spring/build.gradle
  spring/src/main/java/umc/spring/apiPayload/ApiResponse.java
  spring/src/main/java/umc/spring/apiPayload/code/BaseCode.java
  spring/src/main/java/umc/spring/apiPayload/code/BaseErrorCode.java
  spring/src/main/java/umc/spring/apiPayload/code/ErrorReasonDTO.java
  spring/src/main/java/umc/spring/apiPayload/code/ReasonDTO.java
  spring/src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  spring/src/main/java/umc/spring/apiPayload/code/status/SuccessStatus.java
  spring/src/main/java/umc/spring/apiPayload/exception/ExceptionAdvice.java
  spring/src/main/java/umc/spring/apiPayload/exception/GeneralException.java
  spring/src/main/java/umc/spring/apiPayload/exception/handler/TempHandler.java
  spring/src/main/java/umc/spring/converter/TempConverter.java
  spring/src/main/java/umc/spring/service/TempService/TempCommandService.java
  spring/src/main/java/umc/spring/service/TempService/TempCommandServiceImpl.java
  spring/src/main/java/umc/spring/service/TempService/TempQueryService.java
  spring/src/main/java/umc/spring/service/TempService/TempQueryServiceImpl.java
  spring/src/main/java/umc/spring/web/controller/TempRestController.java
  spring/src/main/java/umc/spring/web/dto/TempRequest.java
  spring/src/main/java/umc/spring/web/dto/TempResponse.java
Labels: ✨ Chapter07

#28 Randy/#8
  build.gradle
  src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/spring/apiPayload/exception/handler/FoodCategoryHandler.java
  src/main/java/umc/spring/config/SwaggerConfig.java
  src/main/java/umc/spring/converter/MemberConverter.java
  src/main/java/umc/spring/converter/MemberPreferConverter.java
  src/main/java/umc/spring/domain/Member.java
  src/main/java/umc/spring/domain/enums/Gender.java
  src/main/java/umc/spring/domain/mapping/MemberPrefer.java
  src/main/java/umc/spring/repository/FoodCategoryRepository/FoodCategoryRepository.java
  src/main/java/umc/spring/service/MemberService/MemberCommandService.java
  src/main/java/umc/spring/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/umc/spring/validation/annotation/ExistCategories.java
  src/main/java/umc/spring/validation/validator/CategoriesExistValidator.java
  src/main/java/umc/spring/web/controller/MemberRestController.java
  src/main/java/umc/spring/web/dto/MemberRequestDTO.java
  src/main/java/umc/spring/web/dto/MemberResponseDTO.java
Labels: ✨ Chapter08

#51 [Woody] Chpater 8. 특정 지역 가게 추가 API 구현 미션
  spring/src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  spring/src/main/java/umc/spring/apiPayload/exception/handler/RegionHandler.java
  spring/src/main/java/umc/spring/converter/StoreConverter.java
  spring/src/main/java/umc/spring/repository/RegionRepository/RegionRepository.java
  spring/src/main/java/umc/spring/service/StoreService/StoreCommandService.java
  spring/src/main/java/umc/spring/service/StoreService/StoreCommandServiceImpl.java
  spring/src/main/java/umc/spring/validation/annotation/ExistRegions.java
  spring/src/main/java/umc/spring/validation/validator/RegionsExistValidator.java
  spring/src/main/java/umc/spring/web/controller/StoreRestController.java
  spring/src/main/java/umc/spring/web/dto/StoreRequestDTO.java
  spring/src/main/java/umc/spring/web/dto/StoreResponseDTO.java
Labels: ✨ Chapter08

#44 [Bingseok] Chapter 8. 특정 지역 가게 추가 API 구현
  src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/spring/apiPayload/exception/handler/RegionHandler.java
  src/main/java/umc/spring/converter/StoreConverter.java
  src/main/java/umc/spring/domain/Store.java
  src/main/java/umc/spring/repository/RegionRepository/RegionRepository.java
  src/main/java/umc/spring/service/RegionService/RegionService.java
  src/main/java/umc/spring/service/RegionService/RegionServiceImpl.java
  src/main/java/umc/spring/service/StoreService/StoreService.java
  src/main/java/umc/spring/service/StoreService/StoreServiceImpl.java
  src/main/java/umc/spring/validation/annotation/ExistRegions.java
  src/main/java/umc/spring/validation/validator/RegionsExistValidator.java
  src/main/java/umc/spring/web/controller/StoreController.java
  src/main/java/umc/spring/web/dto/StoreDTO/StoreRequestDTO.java
  src/main/java/umc/spring/web/dto/StoreDTO/StoreResponseDTO.java
Labels: ✨ Chapter08

#33 [Randy] Chpater 8. 가게 리뷰 추가 API 미션
  src/main/java/umc/spring/converter/ReviewConverter.java
  src/main/java/umc/spring/service/ReviewService/ReviewCommandService.java
  src/main/java/umc/spring/service/ReviewService/ReviewCommandServiceImpl.java
  src/main/java/umc/spring/web/controller/ReviewRestController.java
  src/main/java/umc/spring/web/dto/ReviewRequestDTO.java
  src/main/java/umc/spring/web/dto/ReviewResponseDTO.java
Labels: ✨ Chapter08, :sparkles: feature

#39 [Randy] Chpater 8. 가게미션 도전추가 API 미션
  src/main/java/umc/spring/converter/MemberMissionConverter.java
  src/main/java/umc/spring/repository/MemberRepository/MemberMissionRepository.java
  src/main/java/umc/spring/service/MemberMisisonService/MemberMissionCommandService.java
  src/main/java/umc/spring/service/MemberMisisonService/MemberMissionCommandServiceImpl.java
  src/main/java/umc/spring/web/controller/MemberMissionRestController.java
  src/main/java/umc/spring/web/dto/MemberMissionRequestDTO.java
  src/main/java/umc/spring/web/dto/MemberMissionResponseDTO.java
Labels: ✨ Chapter08, :sparkles: feature

#57 [nunu] Chpater 8. 리뷰 추가하기 API 구현 미션
  spring/build.gradle
  spring/src/main/generated/umc/spring/domain/QMission.java
  spring/src/main/generated/umc/spring/domain/QRestaurantImg.java
  spring/src/main/java/umc/spring/apiPayload/code/status/SuccessStatus.java
  spring/src/main/java/umc/spring/config/SwaggerConfig.java
  spring/src/main/java/umc/spring/converter/ReviewConverter.java
  spring/src/main/java/umc/spring/dto/restaurantDTO/RestaurantDTO.java
  spring/src/main/java/umc/spring/dto/reviewDTO/ReviewRequestDTO.java
  spring/src/main/java/umc/spring/dto/reviewDTO/ReviewResponseDTO.java
  spring/src/main/java/umc/spring/handler/annotation/RestaurantExists.java
  spring/src/main/java/umc/spring/handler/resolver/RestaurantExistsValidator.java
  spring/src/main/java/umc/spring/repository/MemberRepository.java
  spring/src/main/java/umc/spring/repository/reviewRepository/ReviewRepository.java
  spring/src/main/java/umc/spring/service/reviewService/ReviewService.java
  spring/src/main/java/umc/spring/service/reviewService/ReviewServiceImpl.java
  spring/src/main/java/umc/spring/web/controller/ReviewController.java
Labels: ✨ Chapter08, :sparkles: feature

#34 [Randy] Chpater 8. 가게 미션 추가 API 미션
  src/main/java/umc/spring/converter/MissionConverter.java
  src/main/java/umc/spring/service/MissionService/MissionCommandService.java
  src/main/java/umc/spring/service/MissionService/MissionCommandServiceImpl.java
  src/main/java/umc/spring/web/controller/MissionRestController.java
  src/main/java/umc/spring/web/dto/MissionRequestDTO.java
  src/main/java/umc/spring/web/dto/MissionResponseDTO.java
Labels: ✨ Chapter08, :sparkles: feature

#52 [Woody] Chpater 8. 가게에 리뷰 추가하기 API 구현 미션
  spring/src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  spring/src/main/java/umc/spring/apiPayload/exception/handler/StoreHandler.java
  spring/src/main/java/umc/spring/converter/ReviewConverter.java
  spring/src/main/java/umc/spring/service/ReviewService/ReviewCommandService.java
  spring/src/main/java/umc/spring/service/ReviewService/ReviewCommandServiceImpl.java
  spring/src/main/java/umc/spring/validation/annotation/ExistStores.java
  spring/src/main/java/umc/spring/validation/validator/StoresValidator.java
  spring/src/main/java/umc/spring/web/controller/ReviewRestController.java
  spring/src/main/java/umc/spring/web/dto/ReviewRequestDTO.java
  spring/src/main/java/umc/spring/web/dto/ReviewResponseDTO.java
Labels: ✨ Chapter08

#58 Woody/#48 feat 가게의 미션 도전중 미션에 추가하기
  spring/src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  spring/src/main/java/umc/spring/apiPayload/exception/handler/MemberHandler.java
  spring/src/main/java/umc/spring/apiPayload/exception/handler/MissionHandler.java
  spring/src/main/java/umc/spring/converter/MemberMissionConverter.java
  spring/src/main/java/umc/spring/service/MemberMissionService/MemberMissionCommandService.java
  spring/src/main/java/umc/spring/service/MemberMissionService/MemberMissionCommandServiceImpl.java
  spring/src/main/java/umc/spring/validation/annotation/ProgressMemberMission.java
  spring/src/main/java/umc/spring/validation/validator/MemberMissionProgressedValidator.java
  spring/src/main/java/umc/spring/web/controller/MemberMissionRestController.java
  spring/src/main/java/umc/spring/web/dto/MemberMissionRequestDTO.java
  spring/src/main/java/umc/spring/web/dto/MemberMissionResponseDTO.java
Labels: ✨ Chapter08

#61 [nunu] Chpater 8. 가게에 미션 추가하기 API 구현 미션
  spring/src/main/java/umc/spring/apiPayload/code/status/SuccessStatus.java
  spring/src/main/java/umc/spring/converter/MissionConverter.java
  spring/src/main/java/umc/spring/dto/missionDTO/MissionRequestDTO.java
  spring/src/main/java/umc/spring/dto/missionDTO/MissionResponseDTO.java
  spring/src/main/java/umc/spring/repository/MissionRepository.java
  spring/src/main/java/umc/spring/service/missionService/MissionService.java
  spring/src/main/java/umc/spring/service/missionService/MissionServiceImpl.java
  spring/src/main/java/umc/spring/web/controller/MissionController.java
Labels: ✨ Chapter08, :sparkles: feature

#64 [nunu] Chpater 8. 챌린지 중인 미션으로 추가하기 API 구현
  spring/src/main/java/umc/spring/apiPayload/code/status/SuccessStatus.java
  spring/src/main/java/umc/spring/converter/MemberMissionConverter.java
  spring/src/main/java/umc/spring/dto/memberMissionDTO/MemberMissionRequestDTO.java
  spring/src/main/java/umc/spring/dto/memberMissionDTO/MemberMissionResponseDTO.java
  spring/src/main/java/umc/spring/repository/MemberMissionRepository.java
  spring/src/main/java/umc/spring/service/memberMissionService/MemberMissionService.java
  spring/src/main/java/umc/spring/service/memberMissionService/MemberMissionServiceImpl.java
  spring/src/main/java/umc/spring/web/controller/MemberMissionController.java
Labels: ✨ Chapter08, :sparkles: feature

#68 [Randy] Chapter 9. API & Paging
  src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/spring/converter/StoreConverter.java
  src/main/java/umc/spring/repository/ReviewRepository/ReviewRepository.java
  src/main/java/umc/spring/service/StoreService/StoreQueryService.java
  src/main/java/umc/spring/service/StoreService/StoreQueryServiceImpl.java
  src/main/java/umc/spring/validation/annotation/ExistStore.java
  src/main/java/umc/spring/validation/validator/StoreExistValidator.java
  src/main/java/umc/spring/web/controller/StoreRestController.java
  src/main/java/umc/spring/web/dto/StoreRequestDTO.java
  src/main/java/umc/spring/web/dto/StoreResponseDTO.java
Labels: ✨ Chapter09

#63 [Woody] Chapter 9. 가게의 리뷰 조회하기 API {실습}
  spring/src/main/java/umc/spring/converter/ReviewConverter.java
  spring/src/main/java/umc/spring/repository/ReviewRepository/ReviewRepository.java
  spring/src/main/java/umc/spring/service/ReviewService/ReviewQueryService.java
  spring/src/main/java/umc/spring/service/ReviewService/ReviewQueryServiceImpl.java
  spring/src/main/java/umc/spring/validation/annotation/ExistStores.java
  spring/src/main/java/umc/spring/validation/validator/StoresExistValidator.java
  spring/src/main/java/umc/spring/web/controller/ReviewRestController.java
  spring/src/main/java/umc/spring/web/dto/ReviewResponseDTO.java
Labels: ✨ Chapter09

#88 [Bingseok] Chapter 9. 가게 리뷰 목록 조회 API (실습)
  src/main/java/umc/spring/converter/StoreConverter.java
  src/main/java/umc/spring/repository/ReviewRepository/ReviewRepository.java
  src/main/java/umc/spring/service/StoreService/StoreService.java
  src/main/java/umc/spring/service/StoreService/StoreServiceImpl.java
  src/main/java/umc/spring/web/controller/StoreController.java
  src/main/java/umc/spring/web/dto/ReviewDTO/ReviewResponseDTO.java
Labels: ✨ Chapter09

#101 [Bingseok] Chapter 9. 진행 중인 미션 진행 완료로 바꾸기 API
  src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/spring/converter/MemberConverter.java
  src/main/java/umc/spring/repository/MemberMissionRepository/MemberMissionRepository.java
  src/main/java/umc/spring/service/MemberMissionService/MemberMissionService.java
  src/main/java/umc/spring/service/MemberMissionService/MemberMissionServiceImpl.java
  src/main/java/umc/spring/validation/annotation/CheckPage.java
  src/main/java/umc/spring/validation/validator/CheckPageValidator.java
  src/main/java/umc/spring/web/controller/MemberMissionController.java
  src/main/java/umc/spring/web/dto/MissionDTO/MissionResponseDTO.java
Labels: ✨ Chapter09, :sparkles: feature

#70 [Randy] Chapter 9. 내가 작성한 리뷰 목록 API 미션
  src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/spring/apiPayload/exception/handler/PageHandler.java
  src/main/java/umc/spring/repository/ReviewRepository/ReviewRepository.java
  src/main/java/umc/spring/service/ReviewService/ReviewQueryService.java
  src/main/java/umc/spring/service/ReviewService/ReviewQueryServiceImpl.java
  src/main/java/umc/spring/validation/annotation/CheckPage.java
  src/main/java/umc/spring/validation/validator/PageCheckValidator.java
  src/main/java/umc/spring/web/controller/ReviewRestController.java
  src/main/java/umc/spring/web/controller/StoreRestController.java
Labels: ✨ Chapter09, :sparkles: feature

#94 [Bingseok] Chapter 9. 내가 작성한 리뷰 목록 API
  src/main/java/umc/spring/Application.java
  src/main/java/umc/spring/converter/ReviewConverter.java
  src/main/java/umc/spring/converter/TempConverter.java
  src/main/java/umc/spring/repository/ReviewRepository/ReviewRepository.java
  src/main/java/umc/spring/service/MemberSevice/MemberService.java
  src/main/java/umc/spring/service/MemberSevice/MemberServiceImpl.java
  src/main/java/umc/spring/service/TempService/TempCommandService.java
  src/main/java/umc/spring/service/TempService/TempCommandServiceImpl.java
  src/main/java/umc/spring/service/TempService/TempQueryService.java
  src/main/java/umc/spring/service/TempService/TempQueryServiceImpl.java
  src/main/java/umc/spring/validation/annotation/CheckPage.java
  src/main/java/umc/spring/web/controller/MemberController.java
  src/main/java/umc/spring/web/controller/TempRestController.java
  src/main/java/umc/spring/web/dto/TempRequest.java
  src/main/java/umc/spring/web/dto/TempResponse.java
Labels: ✨ Chapter09, :sparkles: feature

#97 [Bingseok] Chapter 9. 특정 가게 미션 목록 API
  src/main/java/umc/spring/converter/MissionConverter.java
  src/main/java/umc/spring/converter/StoreConverter.java
  src/main/java/umc/spring/repository/MissionRepository/MissionRepository.java
  src/main/java/umc/spring/service/StoreService/StoreService.java
  src/main/java/umc/spring/service/StoreService/StoreServiceImpl.java
  src/main/java/umc/spring/web/controller/StoreController.java
  src/main/java/umc/spring/web/dto/MissionDTO/MissionResponseDTO.java
Labels: ✨ Chapter09, :sparkles: feature

#99 [Bingseok] Chapter 9. 내가 진행 중인 미션 목록 API
  src/main/java/umc/spring/repository/MemberMissionRepository/MemberMissionRepository.java
  src/main/java/umc/spring/service/MemberMissionService/MemberMissionService.java
  src/main/java/umc/spring/service/MemberMissionService/MemberMissionServiceImpl.java
  src/main/java/umc/spring/service/MemberSevice/MemberServiceImpl.java
  src/main/java/umc/spring/web/controller/MemberMissionController.java
Labels: ✨ Chapter09, :sparkles: feature

#66 [Nunu] Chapter 9. 가게의 리뷰 조회하기 API (실습)
  spring/build.gradle
  spring/src/main/java/umc/spring/apiPayload/code/status/SuccessStatus.java
  spring/src/main/java/umc/spring/config/ValidatorConfig.java
  spring/src/main/java/umc/spring/converter/ReviewConverter.java
  spring/src/main/java/umc/spring/dto/reviewDTO/ReviewRequestDTO.java
  spring/src/main/java/umc/spring/dto/reviewDTO/ReviewResponseDTO.java
  spring/src/main/java/umc/spring/handler/resolver/RestaurantExistsValidator.java
  spring/src/main/java/umc/spring/repository/reviewRepository/ReviewRepository.java
  spring/src/main/java/umc/spring/service/reviewService/ReviewService.java
  spring/src/main/java/umc/spring/service/reviewService/ReviewServiceImpl.java
  spring/src/main/java/umc/spring/web/controller/RestaurantController.java
  spring/src/main/java/umc/spring/web/controller/ReviewController.java
Labels: ✨ Chapter09, :sparkles: feature

#93 [Nunu] Chapter 9. 진행 중인 미션 진행 완료로 바꾸기 API
  spring/src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  spring/src/main/java/umc/spring/apiPayload/code/status/SuccessStatus.java
  spring/src/main/java/umc/spring/apiPayload/exception/ExceptionAdvice.java
  spring/src/main/java/umc/spring/config/WebConfig.java
  spring/src/main/java/umc/spring/converter/MemberMissionConverter.java
  spring/src/main/java/umc/spring/domain/mapping/MemberMission.java
  spring/src/main/java/umc/spring/dto/memberMissionDTO/MemberMissionResponseDTO.java
  spring/src/main/java/umc/spring/handler/annotation/CheckPage.java
  spring/src/main/java/umc/spring/handler/resolver/CheckPageArgumentResolver.java
  spring/src/main/java/umc/spring/handler/resolver/CheckPageValidator.java
  spring/src/main/java/umc/spring/handler/resolver/CustomHandlerMethodResolverPrioritizer.java
  spring/src/main/java/umc/spring/repository/MemberMissionRepository.java
  spring/src/main/java/umc/spring/service/memberMissionService/MemberMissionService.java
  spring/src/main/java/umc/spring/service/memberMissionService/MemberMissionServiceImpl.java
  spring/src/main/java/umc/spring/service/missionService/MissionServiceImpl.java
  spring/src/main/java/umc/spring/service/restaurantService/RestaurantServiceImpl.java
  spring/src/main/java/umc/spring/service/reviewService/ReviewServiceImpl.java
  spring/src/main/java/umc/spring/web/controller/MemberMissionController.java
  spring/src/main/java/umc/spring/web/controller/MissionController.java
  spring/src/main/java/umc/spring/web/controller/RestaurantController.java
  spring/src/main/java/umc/spring/web/controller/ReviewController.java
  spring/src/main/resources/application.yml
Labels: ✨ Chapter09, :sparkles: feature
